export const Candidate_data = [
  {
    CandidateID: 1,
    CandidateName: 'Nguyễn Văn A',
    Gender: '0',
    Birthday: '1995-05-15',
    Mobile: '0987123456',
    Email: 'nguyenvana@gmail.com',
    JobPositionName: 'Nhân viên kinh doanh',
    RecruitmentName: 'Kinh doanh khu vực Hà Nội',
    RecruitmentRoundName: 'Phỏng vấn HR',
    Rating: '5',
    applyDate: '2024-10-01',
    isRecruited: true,
  },
  {
    CandidateID: 2,
    CandidateName: 'Trần Thị Bích',
    Gender: '1',
    Birthday: '2000-09-22',
    Mobile: '0978456123',
    Email: 'bich.tran@example.com',
    JobPositionName: 'Thực tập sinh Marketing',
    RecruitmentName: 'Digital Marketing 2025',
    RecruitmentRoundName: 'Vòng hồ sơ',
    Rating: '5',
    applyDate: '2024-10-01',
    hasMessage: true,
  },
  {
    CandidateID: 3,
    CandidateName: 'Lê Minh Cường',
    Gender: '0',
    Birthday: '1998-02-10',
    Mobile: '0912345678',
    Email: 'cuong.le@example.com',
    JobPositionName: 'Frontend Developer',
    RecruitmentName: 'Tuyển dev VueJS 2025',
    RecruitmentRoundName: 'Phỏng vấn kỹ thuật',
    Rating: '5',
    applyDate: '2024-10-01',
    isNew: true,
  },
  {
    CandidateID: 4,
    CandidateName: 'Phạm Thùy Dung',
    Gender: '1',
    Birthday: '1996-11-05',
    Mobile: '0909234567',
    Email: 'dung.pham@example.com',
    JobPositionName: 'Nhân viên Hành chính - Nhân sự',
    RecruitmentName: 'Khối văn phòng HN',
    RecruitmentRoundName: 'Vòng test nghiệp vụ',
    Rating: '5',
    applyDate: '2024-10-01',
  },
  {
    CandidateID: 5,
    CandidateName: 'Hoàng Đức Long',
    Gender: '0',
    Birthday: '1994-03-28',
    Mobile: '0933456789',
    Email: 'long.hoang@example.com',
    JobPositionName: 'Backend Developer',
    RecruitmentName: 'Tuyển kỹ sư Node.js',
    RecruitmentRoundName: 'Phỏng vấn kỹ thuật',
    Rating: '5',
    applyDate: '2024-10-01',
  },
]
