export const Candidate_data = [
  {
    CandidateID: 1,
    CandidateName: 'Nguyễn Văn A',
    Mobile: '0987123456',
    Email: 'nguyenvana@gmail.com',
    JobPositionName: 'Nhân viên kinh doanh',
    RecruitmentName: 'Kinh doanh khu vực Hà Nội',
    RecruitmentRoundName: 'Phỏng vấn HR',
  },
  {
    CandidateID: 2,
    CandidateName: 'Trần Thị Bích',
    Mobile: '0978456123',
    Email: 'bich.tran@example.com',
    JobPositionName: 'Thực tập sinh Marketing',
    RecruitmentName: 'Digital Marketing 2025',
    RecruitmentRoundName: 'Vòng hồ sơ',
  },
  {
    CandidateID: 3,
    CandidateName: 'Lê Minh Cường',
    Mobile: '0912345678',
    Email: 'cuong.le@example.com',
    JobPositionName: 'Frontend Developer',
    RecruitmentName: 'Tuyển dev VueJS 2025',
    RecruitmentRoundName: 'Phỏng vấn kỹ thuật',
  },
  {
    CandidateID: 4,
    CandidateName: 'Phạm Thùy Dung',
    Mobile: '0909234567',
    Email: 'dung.pham@example.com',
    JobPositionName: 'Nhân viên Hành chính - Nhân sự',
    RecruitmentName: 'Khối văn phòng HN',
    RecruitmentRoundName: 'Vòng test nghiệp vụ',
  },
  {
    CandidateID: 5,
    CandidateName: 'Hoàng Đức Long',
    Mobile: '0933456789',
    Email: 'long.hoang@example.com',
    JobPositionName: 'Backend Developer',
    RecruitmentName: 'Tuyển kỹ sư Node.js',
    RecruitmentRoundName: 'Phỏng vấn kỹ thuật',
  },
]
